# SPDX-License-Identifier: MIT
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
linters:
  enable:
    - gofmt
    - goheader
    - govet
    - dupword
linters-settings:
  goheader:
    template: |
     SPDX-License-Identifier: MIT