# SPDX-License-Identifier: MIT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: docker.pkg.github.com/mercedes-benz/kosmoo/kosmoo
  newName: other/kosmoo
  newTag: new